version: '3.8'

services:
  api:
    build: .
    # No exponemos puertos directamente - Traefik lo maneja
    volumes:
      - /mnt/efs/json-storage:/mnt/efs/json-storage
    environment:
      - STORAGE_PATH=/mnt/efs/json-storage
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - web
    labels:
      # Habilitar Traefik para este contenedor
      - "traefik.enable=true"
      
      # Router HTTP
      - "traefik.http.routers.api.rule=Host(`api.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.middlewares=redirect-to-https"
      
      # Router HTTPS
      - "traefik.http.routers.api-secure.rule=Host(`api.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.api-secure.entrypoints=websecure"
      - "traefik.http.routers.api-secure.tls=true"
      - "traefik.http.routers.api-secure.tls.certresolver=letsencrypt"
      
      # Servicio
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.http.services.api.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.api.loadbalancer.healthcheck.interval=10s"
      
      # Middleware para redirección HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      
      # Metadata
      - "traefik.docker.network=web"

networks:
  web:
    external: true